# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
ഹായ് [firstname], എന്റെ പേര്  [botname]! എന്നെ ഉപയോഗിക്കേണ്ടത് എങ്ങനെ ആണെന്നുള്ളതിൽ എന്തേലും സംശയം ഉണ്ടെങ്കിൽ /help കൊടുത്താൽ മതിയാകും... 
എന്റെ ന്യൂ ഫീച്ചേർസ് ചാനലിൽ @Ansiltech_official ഇടുന്നതായിരിക്കും. സംശയങ്ങൾക്ക് @ansiltechteam എന്ന ഗ്രൂപ്പിൽ വരാവുന്നതാണ്.....

എന്നെ നോക്കി നടത്തുന്നത്  [He is] ആണ് . എന്നെ നിർമിച്ചിരിക്കുന്നത് python3യിൽ 
python-telegram-bot library ഉപയോഗിച്ചാണ്.... ഞാൻ പൂർണമായും opensource ആണ്.. എന്റെ കോഡ് നിങ്ങൾക്ക് ഇവിടെ കാണാവുന്നതാണ്...
എന്നെ ഉപയോഗിക്കാൻ ആവിശ്യമായ commandകൾ അറിയാൻ /help കൊടുത്താൽ മതിയാകും..
വിവരങ്ങൾക്കായി /info  ഉപയോഗിക്കാവുന്നതാണ്...
